# Generated by Django 5.1.7 on 2025-03-24 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='Дома', max_length=200, verbose_name='Место')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=200, verbose_name='Действие')),
                ('nice_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('complete_time', models.DurationField(blank=True, null=True, verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(blank=True, default=True, null=True, verbose_name='Признак публичности')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habits', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
