name: habit_tracker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:13
        env:
          POSTGRES_DB: habit_tracker
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 7627
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U myuser" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DEBUG=${{ secrets.DEBUG }}" >> .env
          
          echo "POSTGRES_DB=${{ secrets.POSTGRES_NAME }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          
          echo "BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env


      - name: Build and push Docker images
        run: |
          docker compose build
          docker compose push

    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.SSH_KEY }}

        - name: Deploy to Server
          run: |
            ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'

              cd /root/habit_tracker

              sudo docker compose down
              sudo docker compose pull
              sudo docker compose up -d --remove-orphans

              sudo docker image prune -f
            EOF